export const translations = {
    en: {
        title: "Immigration Job Matcher",
        subtitle: "Upload your resume and let AI find your perfect job match",
        uploadResume: "Upload Your Resume",
        uploadHint: "PDF, Word, or Image • Any Language",
        analyzeButton: "Analyze Resume",
        analyzing: "Analyzing Resume...",
        analysisComplete: "Analysis Complete!",
        originalLanguage: "Original Language",
        skills: "Skills",
        experience: "Experience",
        education: "Education",
        usEquivalents: "US Equivalents & Recommendations",
        degreeEquivalent: "Degree Equivalent",
        recommendedCerts: "Recommended Certifications",
        recommendedJobs: "Recommended Job Titles",
        suggestions: "Suggestions for US Employers",
        chatTitle: "Job Search Assistant",
        chatSubtitle: "Always here to help",
        chatPlaceholder: "Ask me anything...",
        chatWelcome: "Hello! I'm your job search assistant.",
        matchingJobs: "Matching Jobs for You",
        searchingJobs: "Searching for jobs...",
        viewJob: "View Job",
        noJobsFound: "No jobs found.",
        languageName: "English"
    },
    es: {
        title: "Buscador de Empleos para Inmigrantes",
        subtitle: "Sube tu currículum y deja que la IA encuentre tu trabajo ideal",
        uploadResume: "Subir Currículum",
        uploadHint: "PDF, Word o Imagen • Cualquier Idioma",
        analyzeButton: "Analizar Currículum",
        analyzing: "Analizando Currículum...",
        analysisComplete: "¡Análisis Completado!",
        originalLanguage: "Idioma Original",
        skills: "Habilidades",
        experience: "Experiencia",
        education: "Educación",
        usEquivalents: "Equivalentes en EE. UU. y Recomendaciones",
        degreeEquivalent: "Equivalente de Título",
        recommendedCerts: "Certificaciones Recomendadas",
        recommendedJobs: "Títulos de Trabajo Recomendados",
        suggestions: "Sugerencias para Empleadores de EE. UU.",
        chatTitle: "Asistente de Búsqueda de Empleo",
        chatSubtitle: "Siempre aquí para ayudar",
        chatPlaceholder: "Pregúntame lo que sea...",
        chatWelcome: "¡Hola! Soy tu asistente de búsqueda de empleo.",
        matchingJobs: "Empleos para Ti",
        searchingJobs: "Buscando empleos...",
        viewJob: "Ver Empleo",
        noJobsFound: "No se encontraron empleos.",
        languageName: "Spanish"
    },
    fr: {
        title: "Recherche d'Emploi pour Immigrés",
        subtitle: "Téléchargez votre CV et laissez l'IA trouver votre emploi idéal",
        uploadResume: "Télécharger le CV",
        uploadHint: "PDF, Word ou Image • Toute Langue",
        analyzeButton: "Analyser le CV",
        analyzing: "Analyse du CV...",
        analysisComplete: "Analyse Terminée !",
        originalLanguage: "Langue Originale",
        skills: "Compétences",
        experience: "Expérience",
        education: "Éducation",
        usEquivalents: "Équivalents US et Recommandations",
        degreeEquivalent: "Équivalent du Diplôme",
        recommendedCerts: "Certifications Recommandées",
        recommendedJobs: "Titres de Postes Recommandés",
        suggestions: "Suggestions pour les Employeurs US",
        chatTitle: "Assistant Recherche d'Emploi",
        chatSubtitle: "Toujours là pour vous aider",
        chatPlaceholder: "Posez-moi une question...",
        chatWelcome: "Bonjour ! Je suis votre assistant de recherche d'emploi.",
        matchingJobs: "Emplois correspondants",
        searchingJobs: "Recherche d'emplois...",
        viewJob: "Voir l'Offre",
        noJobsFound: "Aucun emploi trouvé.",
        languageName: "French"
    },
    ar: {
        title: "متطابق وظائف المهاجرين",
        subtitle: "ارفع سيرتك الذاتية ودع الذكاء الاصطناعي يجد لك الوظيفة المثالية",
        uploadResume: "تحميل السيرة الذاتية",
        uploadHint: "PDF أو Word أو صورة • أي لغة",
        analyzeButton: "تحليل السيرة الذاتية",
        analyzing: "جاري تحليل السيرة الذاتية...",
        analysisComplete: "اكتمل التحليل!",
        originalLanguage: "اللغة الأصلية",
        skills: "المهارات",
        experience: "الخبرة",
        education: "التعليم",
        usEquivalents: "المعادلات والتوصيات في الولايات المتحدة",
        degreeEquivalent: "معادل الشهادة",
        recommendedCerts: "الشهادات الموصى بها",
        recommendedJobs: "المسميات الوظيفية الموصى بها",
        suggestions: "اقتراحات لأصحاب العمل في الولايات المتحدة",
        chatTitle: "مساعد البحث عن وظيفة",
        chatSubtitle: "هنا للمساعدة دائماً",
        chatPlaceholder: "اسألني عن أي شيء...",
        chatWelcome: "مرحباً! أنا مساعدك في البحث عن وظيفة.",
        matchingJobs: "وظائف مطابقة لك",
        searchingJobs: "جاري البحث عن وظائف...",
        viewJob: "عرض الوظيفة",
        noJobsFound: "لم يتم العثور على وظائف.",
        languageName: "Arabic"
    },
    zh: {
        title: "移民职位匹配器",
        subtitle: "上传您的简历，让人工智能为您找到完美的工作",
        uploadResume: "上传简历",
        uploadHint: "PDF、Word 或图片 • 任何语言",
        analyzeButton: "分析简历",
        analyzing: "正在分析简历...",
        analysisComplete: "分析完成！",
        originalLanguage: "原始语言",
        skills: "技能",
        experience: "工作经验",
        education: "教育背景",
        usEquivalents: "美国学历认证与建议",
        degreeEquivalent: "学位等效",
        recommendedCerts: "推荐证书",
        recommendedJobs: "推荐职位名称",
        suggestions: "对美国雇主的建议",
        chatTitle: "求职助手",
        chatSubtitle: "随时为您提供帮助",
        chatPlaceholder: "问我任何问题...",
        chatWelcome: "您好！我是您的求职助手。",
        matchingJobs: "为您匹配的职位",
        searchingJobs: "正在搜索职位...",
        viewJob: "查看职位",
        noJobsFound: "未找到职位。",
        languageName: "Chinese"
    },
    hi: {
        title: "प्रवासी जॉब मैचर",
        subtitle: "अपना रिज्यूमे अपलोड करें और AI को आपके लिए सही जॉब खोजने दें",
        uploadResume: "रिज्यूमे अपलोड करें",
        uploadHint: "PDF, Word या इमेज • कोई भी भाषा",
        analyzeButton: "रिज्यूमे का विश्लेषण करें",
        analyzing: "रिज्यूमे का विश्लेषण किया जा रहा है...",
        analysisComplete: "विश्लेषण पूरा हुआ!",
        originalLanguage: "मूल भाषा",
        skills: "कौशल",
        experience: "अनुभव",
        education: "शिक्षा",
        usEquivalents: "अमेरिकी समकक्ष और सिफारिशें",
        degreeEquivalent: "डिग्री समकक्ष",
        recommendedCerts: "अनुशंसित प्रमाणन",
        recommendedJobs: "अनुशंसित जॉब टाइटल्स",
        suggestions: "अमेरिकी नियोक्ताओं के लिए सुझाव",
        chatTitle: "जॉब सर्च असिस्टेंट",
        chatSubtitle: "हमेशा आपकी मदद के लिए यहाँ है",
        chatPlaceholder: "मुझसे कुछ भी पूछें...",
        chatWelcome: "नमस्ते! मैं आपका जॉब सर्च असिस्टेंट हूँ।",
        matchingJobs: "आपके लिए मेल खाने वाली नौकरियां",
        searchingJobs: "नौकरियां खोजी जा रही हैं...",
        viewJob: "जॉब देखें",
        noJobsFound: "कोई नौकरी नहीं मिली।",
        languageName: "Hindi"
    }
};
