// ============================================================
// UI translations for all 6 supported languages
// ============================================================
// Keys are intentionally flat (no nesting) so the existing
// `t.someKey` access pattern still works across the codebase.
// Group via prefix: nav*, home*, auth*, an* (analyzer), sb*
// (sidebar), job*, res*, jp* (jobs page), st* (studio), bl*
// (builder), chat*, common*.
//
// Translations are best-effort and should be spot-checked by
// fluent speakers before public launch (especially ar/hi/zh).
// Master copy is English; other languages mirror its structure.
// ============================================================

export const translations = {

    // ========================================================
    // ENGLISH (en) — MASTER
    // ========================================================
    en: {
        // ---- meta ----
        languageName: 'English',
        title: 'EmployAI',
        subtitle: "Upload your resume and let AI find your perfect job match",

        // ---- navigation ----
        navHome: 'Home',
        navAnalyze: 'Analyze',
        navStudio: 'Studio',
        navResumes: 'Resumes',
        navJobs: 'Jobs',
        navLogIn: 'Log in',
        navSignUp: 'Sign up',
        navLogOut: 'Log out',
        navToggleLight: 'Switch to light mode',
        navToggleDark: 'Switch to dark mode',

        // ---- HOME (marketing) ----
        homeBadge: 'Built for immigrants · Works in 6 languages',
        homeHeroTitle: "The job market doesn't have to be confusing in a new country.",
        homeHeroSub: 'Upload your resume in any language. EmployAI translates it, matches you to real US jobs, and coaches you toward better offers — for free.',
        homeHeroPlaceholder: 'What kind of work are you looking for? (e.g. remote backend roles in fintech)',
        homeCtaUpload: 'Upload my resume — free',
        homeCtaContinue: 'Continue to Analyze',
        homeIntentHint: "We'll use that to bias your job matches.",
        homePopular: 'Popular:',
        homePop1: 'Software Engineer',
        homePop2: 'Registered Nurse',
        homePop3: 'Construction',
        homePop4: 'Accounting',
        homeTrustNoFee: 'No fee. No credit card.',
        homeTrustPrivate: 'We never sell your data',
        homeTrustAnyLang: 'Works in any language',

        homeHowLabel: 'How it works',
        homeHowTitle: 'From your resume to your next job in three steps.',
        homeStep1Title: 'Upload, in any language',
        homeStep1Desc: 'Drop your resume — PDF, Word, or even a photo. We support Spanish, French, Arabic, Chinese, Hindi, and English. We translate and structure it automatically.',
        homeStep2Title: 'See real matched jobs',
        homeStep2Desc: 'We compare your skills to live US job listings using meaning — not just keywords — so a payment-processing engineer in Argentina gets matched to fintech roles, not generic "engineer" results.',
        homeStep3Title: 'Improve and apply',
        homeStep3Desc: 'Your AI coach suggests specific edits to make your resume stronger for US employers — and builds you a properly-formatted US version, ready to download.',

        homeFeaturesLabel: 'Real matching, not keyword soup',
        homeFeaturesTitle: 'See exactly how well each job fits your background — and why.',
        homeFeaturesIntro: 'Most job sites rank by how recently the listing was posted, or how loudly the employer paid to be featured. EmployAI ranks by how well your skills and experience actually match the role.',
        homeFeatBullet1Bold: 'Color-coded match scores',
        homeFeatBullet1: 'see which jobs are worth your time at a glance.',
        homeFeatBullet2Bold: 'Watch scores rise',
        homeFeatBullet2: 'as you accept resume improvements.',
        homeFeatBullet3Bold: 'Save and track',
        homeFeatBullet3: 'applications through interview to offer.',
        homeFeatTopMatches: 'Top matches for you',
        homeFeatPreviewNote: 'Live preview · scored in seconds.',

        homeLangsLabel: 'Languages we speak',
        homeLangsTitle: 'Upload your resume in the language it was written in.',
        homeLangsSub: 'Six languages today. More on the way as we hear from job seekers around the world.',

        homeStoriesLabel: 'Stories',
        homeStoriesTitle: 'From qualified — to hired.',
        homeStoriesFootnote: 'Stories above use placeholder portraits — real testimonials and photos coming as the platform grows.',

        homeFinalTitle: "Start with your resume. We'll handle the rest.",
        homeFinalSub: 'Free to use. Available in six languages. Nothing to install.',
        homeFinalSeeHow: 'See how it works',

        homeFooterDesc: 'A multilingual AI job-search platform built for immigrants navigating the US labor market. Free, private, and human-friendly.',
        homeFooterProduct: 'Product',
        homeFooterHowItWorks: 'How it works',
        homeFooterStudio: 'Resume Studio',
        homeFooterMatching: 'Job matching',
        homeFooterTracking: 'Application tracking',
        homeFooterAbout: 'About',
        homeFooterTeam: 'The team',
        homeFooterMission: 'Mission',
        homeFooterPrivacy: 'Privacy',
        homeFooterGithub: 'GitHub',
        homeFooterDisclaimer: 'EmployAI — Jericho Senior High School project. Not a legal employer or licensed immigration service.',

        // ---- AUTH (login + signup) ----
        authWelcomeBack: 'Welcome back',
        authLoginSub: 'Log in to continue your job search',
        authCreateAccount: 'Create your account',
        authSignupSub: 'Save your profile and track your applications',
        authEmail: 'Email',
        authPassword: 'Password',
        authEmailPh: 'you@example.com',
        authPasswordPh: '••••••••',
        authPasswordCreatePh: 'At least 10 characters',
        authName: 'Name',
        authNameOptional: '(optional)',
        authNamePh: 'Your name',
        authLogIn: 'Log in',
        authLoggingIn: 'Logging in...',
        authCreate: 'Create account',
        authCreating: 'Creating account...',
        authPwTooShort: 'Password must be at least 10 characters',
        authNoAccount: "Don't have an account?",
        authHaveAccount: 'Already have an account?',

        // ---- ANALYZER toolbar / banners ----
        anActive: 'Active',
        anTopMatch: 'top match',
        anJobs: 'jobs',
        anSaved: 'saved',
        anUploadNew: 'Upload new',
        anReRun: 'Re-run search',
        anImproveStudio: 'Improve in Studio',
        anBiasingToward: 'Biasing matches toward:',
        anBiasingForward: "We'll bias matches toward:",
        anClearIntent: 'Clear intent and re-rank',
        anLowMatchTitleA: 'Your top match is only ',
        anLowMatchTitleB: '%.',
        anLowMatchSub: 'Want the AI assistant to suggest specific resume tweaks or alternative job titles to explore?',
        anLowMatchGetTips: 'Get tips',
        anLowMatchDismiss: 'Dismiss',

        // ---- Matched jobs area ----
        anMatchedJobs: 'Matched jobs',
        anSortBest: 'Best match',
        anSortRecent: 'Most recent',
        anSortPay: 'Highest pay',
        anFilters: 'Filters:',
        anFilterRemote: 'Remote',
        anFilterFullTime: 'Full-time',
        anFilter100k: '$100k+',
        anClearAll: 'Clear all',
        anNoMatchesForFilters: 'No jobs match these filters.',
        anClearFilters: 'Clear filters',

        // ---- SIDEBAR (resume profile in /analyze) ----
        sbYourProfile: 'Your profile',
        sbTranslatedFrom: 'Translated from',
        sbSummary: 'Summary',
        sbTargetRoles: 'Target roles',
        sbSkills: 'Skills',
        sbExperience: 'Experience',
        sbEducation: 'Education',
        sbUsEquivalents: 'US Equivalents',
        sbDegree: 'Degree',
        sbRecCerts: 'Recommended certifications',
        sbImproveStudio: 'Improve this resume in the Studio',

        // ---- JobMatches actions ----
        viewJob: 'View Job',
        jobMarkApplied: 'Mark applied',
        jobApplied: 'Applied',
        jobSave: 'Save for later',
        jobUnsave: 'Unsave',
        matchingJobs: 'Matching Jobs for You',
        searchingJobs: 'Searching for jobs...',
        noJobsFound: 'No jobs found.',

        // ---- RESUMES page ----
        resTitle: 'Your resumes',
        resEmpty: 'Upload your first resume to get started.',
        resCount: (n) => `${n} saved. The active one drives job matches and chat.`,
        resUploadNew: 'Upload new',
        resEmptyTitle: 'No resumes yet',
        resEmptyDesc: 'Upload your first resume on the Analyze page. The AI will translate, parse, and find matching jobs.',
        resEmptyCta: 'Upload your first resume',
        resActiveBadge: 'Active',
        resSetActive: 'Set active',
        resRename: 'Rename',
        resDelete: 'Delete',
        resSaveTip: 'Save',
        resCancelTip: 'Cancel',
        resUploadedOn: 'Uploaded',
        resLoading: 'Loading your resumes…',
        resConfirmDelete: (label) => `Delete "${label}"? This can't be undone.`,

        // ---- JOBS page ----
        jpTitle: 'Your jobs',
        jpSub: "Saved bookmarks and applications you're tracking.",
        jpTabSaved: 'Saved',
        jpTabApps: 'Applications',
        jpEmptySaved: 'No saved jobs yet',
        jpEmptySavedDesc: 'Click the heart on any job in your matches to save it for later.',
        jpFindJobs: 'Find jobs',
        jpEmptyApps: 'No applications tracked yet',
        jpEmptyAppsDesc: 'When you apply to a job, click "Mark applied" to track its status here.',
        jpUnsave: 'Unsave',
        jpDelete: 'Delete',
        jpDeleteConfirm: 'Delete this application record?',
        jpNotes: 'Notes',
        jpNotesPh: 'Interview Tuesday, contacted recruiter, etc.',
        jpAppliedOn: 'Applied',
        jpLoading: 'Loading your jobs…',
        jpStatusApplied: 'Applied',
        jpStatusInterviewing: 'Interviewing',
        jpStatusOffered: 'Offered',
        jpStatusRejected: 'Rejected',
        jpStatusWithdrawn: 'Withdrawn',

        // ---- STUDIO (Editor) ----
        stEditing: 'Editing:',
        stManage: 'Manage',
        stReRankJobs: 'Re-rank jobs',
        stBuildUsResume: 'Build US Resume',
        stYourResume: 'Your resume',
        stAiCoach: 'AI Coach',
        stExplainIn: 'Explain in',
        stFocusLabel: 'What should the coach focus on?',
        stFocusOptional: '(optional)',
        stFocusPh: 'e.g. emphasize leadership, make bullets shorter',
        stGetSuggestions: 'Get suggestions',
        stNewSuggestions: 'New suggestions',
        stCoaching: 'Coaching…',
        stCoachEmptyA: 'Click ',
        stCoachEmptyB: ' to see specific ways to strengthen this resume.',
        stCurrently: 'Currently',
        stSuggested: 'Suggested',
        stApply: 'Apply',
        stSkip: 'Skip',
        stTypeSummary: 'Summary',
        stTypeBullet: 'Experience bullet',
        stTypeSkill: 'Skill',
        stTypeNewSkill: 'New skill',
        stTypeTargetRole: 'Target role',
        stTypeCert: 'Certification',
        stVerbRewrite: 'Rewrite',
        stVerbReplace: 'Replace',
        stVerbAdd: 'Add',
        stEmptyTitle: 'No resume to coach yet',
        stEmptyDesc: 'Upload a resume first — the studio will help you improve it line by line.',
        stUploadResumeBtn: 'Upload a resume',
        stLoading: 'Loading studio…',

        // ---- BUILDER modal ----
        blTitle: 'Build US Resume',
        blTemplate: 'Template',
        blTemplateHybrid: 'Hybrid',
        blTemplateChrono: 'Chronological',
        blTemplateSkillsFirst: 'Skills-first',
        blTemplateHybridDesc: 'Skills-led + chronological — best for immigrants',
        blTemplateChronoDesc: 'Classic US format — best for steady careers',
        blTemplateSkillsDesc: 'Functional — best for career changers / gaps',
        blOutputLang: 'Output language',
        blGenerate: 'Generate US-tailored resume',
        blRebuild: 'Rebuild',
        blBuilding: 'Building…',
        blPreviewNote: 'Preview below. Copy as plain text for ATS / job sites, or download .docx for Word.',
        blCopyText: 'Copy text',
        blCopyMd: 'Copy markdown',
        blDownloadDocx: 'Download .docx',

        // ---- existing keys (kept for backwards compatibility) ----
        uploadResume: 'Upload Your Resume',
        uploadHint: 'PDF, Word, or Image • Any Language',
        analyzeButton: 'Analyze Resume',
        analyzing: 'Analyzing Resume...',
        analysisComplete: 'Analysis Complete!',
        originalLanguage: 'Original Language',
        skills: 'Skills',
        experience: 'Experience',
        education: 'Education',
        usEquivalents: 'US Equivalents & Recommendations',
        degreeEquivalent: 'Degree Equivalent',
        recommendedCerts: 'Recommended Certifications',
        recommendedJobs: 'Recommended Job Titles',
        suggestions: 'Suggestions for US Employers',
        chatTitle: 'Job Search Assistant',
        chatSubtitle: 'Always here to help',
        chatPlaceholder: 'Ask me anything...',
        chatWelcome: "Hello! I'm your job search assistant.",
        chatAskCoach: 'Ask the coach',

        // ---- common ----
        commonError: 'Something went wrong. Please try again.',
        commonCopyBlocked: 'Copy failed — your browser may have blocked clipboard access',
    },

    // ========================================================
    // SPANISH (es)
    // ========================================================
    es: {
        languageName: 'Spanish',
        title: 'EmployAI',
        subtitle: 'Sube tu currículum y deja que la IA encuentre tu trabajo ideal',

        navHome: 'Inicio',
        navAnalyze: 'Analizar',
        navStudio: 'Studio',
        navResumes: 'Currículums',
        navJobs: 'Empleos',
        navLogIn: 'Iniciar sesión',
        navSignUp: 'Registrarse',
        navLogOut: 'Cerrar sesión',
        navToggleLight: 'Cambiar a modo claro',
        navToggleDark: 'Cambiar a modo oscuro',

        homeBadge: 'Creado para inmigrantes · Disponible en 6 idiomas',
        homeHeroTitle: 'El mercado laboral no tiene por qué ser confuso en un país nuevo.',
        homeHeroSub: 'Sube tu currículum en cualquier idioma. EmployAI lo traduce, te conecta con empleos reales en EE. UU. y te guía hacia mejores ofertas — gratis.',
        homeHeroPlaceholder: '¿Qué tipo de trabajo buscas? (ej. backend remoto en fintech)',
        homeCtaUpload: 'Subir mi currículum — gratis',
        homeCtaContinue: 'Continuar a Analizar',
        homeIntentHint: 'Lo usaremos para orientar tus coincidencias laborales.',
        homePopular: 'Populares:',
        homePop1: 'Ingeniero de software',
        homePop2: 'Enfermera titulada',
        homePop3: 'Construcción',
        homePop4: 'Contabilidad',
        homeTrustNoFee: 'Sin costo. Sin tarjeta de crédito.',
        homeTrustPrivate: 'Nunca vendemos tus datos',
        homeTrustAnyLang: 'Funciona en cualquier idioma',

        homeHowLabel: 'Cómo funciona',
        homeHowTitle: 'De tu currículum a tu próximo empleo en tres pasos.',
        homeStep1Title: 'Sube, en cualquier idioma',
        homeStep1Desc: 'Arrastra tu currículum — PDF, Word o incluso una foto. Soportamos español, francés, árabe, chino, hindi e inglés. Lo traducimos y estructuramos automáticamente.',
        homeStep2Title: 'Ve empleos reales coincidentes',
        homeStep2Desc: 'Comparamos tus habilidades con ofertas reales en EE. UU. usando significado — no solo palabras clave — para que un ingeniero de pagos en Argentina sea emparejado con roles de fintech, no resultados genéricos.',
        homeStep3Title: 'Mejora y postula',
        homeStep3Desc: 'Tu coach de IA sugiere cambios específicos para fortalecer tu currículum frente a empleadores de EE. UU. — y te genera una versión formateada al estilo estadounidense, lista para descargar.',

        homeFeaturesLabel: 'Coincidencia real, no sopa de palabras clave',
        homeFeaturesTitle: 'Mira con exactitud qué tan bien encaja cada empleo con tu perfil — y por qué.',
        homeFeaturesIntro: 'La mayoría de sitios de empleo ordenan por fecha o por quién pagó más por destacar. EmployAI ordena por qué tan bien tus habilidades y experiencia coinciden con el puesto.',
        homeFeatBullet1Bold: 'Puntuaciones con código de color',
        homeFeatBullet1: 'mira qué empleos valen tu tiempo de un vistazo.',
        homeFeatBullet2Bold: 'Ve subir tus puntuaciones',
        homeFeatBullet2: 'a medida que aceptas mejoras en tu currículum.',
        homeFeatBullet3Bold: 'Guarda y rastrea',
        homeFeatBullet3: 'tus postulaciones desde la entrevista hasta la oferta.',
        homeFeatTopMatches: 'Mejores coincidencias para ti',
        homeFeatPreviewNote: 'Vista previa en vivo · calificado en segundos.',

        homeLangsLabel: 'Idiomas que hablamos',
        homeLangsTitle: 'Sube tu currículum en el idioma en que fue escrito.',
        homeLangsSub: 'Seis idiomas hoy. Más en camino conforme escuchamos a quienes buscan empleo en el mundo.',

        homeStoriesLabel: 'Historias',
        homeStoriesTitle: 'De calificado — a contratado.',
        homeStoriesFootnote: 'Las historias arriba usan retratos de marcador de posición — testimonios reales y fotos vienen pronto.',

        homeFinalTitle: 'Empieza con tu currículum. Nosotros nos encargamos del resto.',
        homeFinalSub: 'Gratis. Disponible en seis idiomas. Nada que instalar.',
        homeFinalSeeHow: 'Ver cómo funciona',

        homeFooterDesc: 'Plataforma multilingüe de búsqueda de empleo con IA, creada para inmigrantes que navegan el mercado laboral de EE. UU. Gratis, privada y amigable.',
        homeFooterProduct: 'Producto',
        homeFooterHowItWorks: 'Cómo funciona',
        homeFooterStudio: 'Resume Studio',
        homeFooterMatching: 'Coincidencia de empleos',
        homeFooterTracking: 'Seguimiento de postulaciones',
        homeFooterAbout: 'Acerca de',
        homeFooterTeam: 'El equipo',
        homeFooterMission: 'Misión',
        homeFooterPrivacy: 'Privacidad',
        homeFooterGithub: 'GitHub',
        homeFooterDisclaimer: 'EmployAI — proyecto de Jericho Senior High School. No es un empleador legal ni un servicio de inmigración con licencia.',

        authWelcomeBack: 'Bienvenido de nuevo',
        authLoginSub: 'Inicia sesión para continuar tu búsqueda de empleo',
        authCreateAccount: 'Crea tu cuenta',
        authSignupSub: 'Guarda tu perfil y rastrea tus postulaciones',
        authEmail: 'Correo electrónico',
        authPassword: 'Contraseña',
        authEmailPh: 'tu@ejemplo.com',
        authPasswordPh: '••••••••',
        authPasswordCreatePh: 'Al menos 8 caracteres',
        authName: 'Nombre',
        authNameOptional: '(opcional)',
        authNamePh: 'Tu nombre',
        authLogIn: 'Iniciar sesión',
        authLoggingIn: 'Iniciando sesión...',
        authCreate: 'Crear cuenta',
        authCreating: 'Creando cuenta...',
        authPwTooShort: 'La contraseña debe tener al menos 10 caracteres',
        authNoAccount: '¿No tienes una cuenta?',
        authHaveAccount: '¿Ya tienes una cuenta?',

        anActive: 'Activo',
        anTopMatch: 'mejor coincidencia',
        anJobs: 'empleos',
        anSaved: 'guardados',
        anUploadNew: 'Subir nuevo',
        anReRun: 'Reejecutar búsqueda',
        anImproveStudio: 'Mejorar en Studio',
        anBiasingToward: 'Orientando coincidencias hacia:',
        anBiasingForward: 'Orientaremos las coincidencias hacia:',
        anClearIntent: 'Borrar intención y reordenar',
        anLowMatchTitleA: 'Tu mejor coincidencia es solo ',
        anLowMatchTitleB: '%.',
        anLowMatchSub: '¿Quieres que el asistente de IA sugiera ajustes específicos a tu currículum o títulos alternativos?',
        anLowMatchGetTips: 'Recibir consejos',
        anLowMatchDismiss: 'Descartar',

        anMatchedJobs: 'Empleos coincidentes',
        anSortBest: 'Mejor coincidencia',
        anSortRecent: 'Más recientes',
        anSortPay: 'Mejor salario',
        anFilters: 'Filtros:',
        anFilterRemote: 'Remoto',
        anFilterFullTime: 'Tiempo completo',
        anFilter100k: '$100k+',
        anClearAll: 'Borrar todos',
        anNoMatchesForFilters: 'Ningún empleo coincide con estos filtros.',
        anClearFilters: 'Borrar filtros',

        sbYourProfile: 'Tu perfil',
        sbTranslatedFrom: 'Traducido del',
        sbSummary: 'Resumen',
        sbTargetRoles: 'Roles objetivo',
        sbSkills: 'Habilidades',
        sbExperience: 'Experiencia',
        sbEducation: 'Educación',
        sbUsEquivalents: 'Equivalentes en EE. UU.',
        sbDegree: 'Título',
        sbRecCerts: 'Certificaciones recomendadas',
        sbImproveStudio: 'Mejorar este currículum en el Studio',

        viewJob: 'Ver Empleo',
        jobMarkApplied: 'Marcar como postulado',
        jobApplied: 'Postulado',
        jobSave: 'Guardar para después',
        jobUnsave: 'Quitar de guardados',
        matchingJobs: 'Empleos para Ti',
        searchingJobs: 'Buscando empleos...',
        noJobsFound: 'No se encontraron empleos.',

        resTitle: 'Tus currículums',
        resEmpty: 'Sube tu primer currículum para comenzar.',
        resCount: (n) => `${n} guardados. El activo dirige las coincidencias y el chat.`,
        resUploadNew: 'Subir nuevo',
        resEmptyTitle: 'Aún no hay currículums',
        resEmptyDesc: 'Sube tu primer currículum en la página Analizar. La IA lo traducirá, lo procesará y encontrará empleos coincidentes.',
        resEmptyCta: 'Subir tu primer currículum',
        resActiveBadge: 'Activo',
        resSetActive: 'Activar',
        resRename: 'Renombrar',
        resDelete: 'Eliminar',
        resSaveTip: 'Guardar',
        resCancelTip: 'Cancelar',
        resUploadedOn: 'Subido',
        resLoading: 'Cargando tus currículums…',
        resConfirmDelete: (label) => `¿Eliminar "${label}"? Esto no se puede deshacer.`,

        jpTitle: 'Tus empleos',
        jpSub: 'Marcadores guardados y postulaciones que estás rastreando.',
        jpTabSaved: 'Guardados',
        jpTabApps: 'Postulaciones',
        jpEmptySaved: 'Aún no hay empleos guardados',
        jpEmptySavedDesc: 'Haz clic en el corazón de cualquier empleo para guardarlo.',
        jpFindJobs: 'Buscar empleos',
        jpEmptyApps: 'Aún no hay postulaciones',
        jpEmptyAppsDesc: 'Cuando postules a un empleo, haz clic en "Marcar como postulado" para rastrearlo aquí.',
        jpUnsave: 'Quitar',
        jpDelete: 'Eliminar',
        jpDeleteConfirm: '¿Eliminar este registro de postulación?',
        jpNotes: 'Notas',
        jpNotesPh: 'Entrevista el martes, contacté reclutador, etc.',
        jpAppliedOn: 'Postulado',
        jpLoading: 'Cargando tus empleos…',
        jpStatusApplied: 'Postulado',
        jpStatusInterviewing: 'Entrevistando',
        jpStatusOffered: 'Oferta recibida',
        jpStatusRejected: 'Rechazado',
        jpStatusWithdrawn: 'Retirado',

        stEditing: 'Editando:',
        stManage: 'Administrar',
        stReRankJobs: 'Reordenar empleos',
        stBuildUsResume: 'Crear Currículum US',
        stYourResume: 'Tu currículum',
        stAiCoach: 'Coach de IA',
        stExplainIn: 'Explicar en',
        stFocusLabel: '¿En qué debe enfocarse el coach?',
        stFocusOptional: '(opcional)',
        stFocusPh: 'ej. enfatizar liderazgo, hacer viñetas más cortas',
        stGetSuggestions: 'Obtener sugerencias',
        stNewSuggestions: 'Nuevas sugerencias',
        stCoaching: 'Asesorando…',
        stCoachEmptyA: 'Haz clic en ',
        stCoachEmptyB: ' para ver formas específicas de fortalecer este currículum.',
        stCurrently: 'Actualmente',
        stSuggested: 'Sugerido',
        stApply: 'Aplicar',
        stSkip: 'Omitir',
        stTypeSummary: 'Resumen',
        stTypeBullet: 'Viñeta de experiencia',
        stTypeSkill: 'Habilidad',
        stTypeNewSkill: 'Nueva habilidad',
        stTypeTargetRole: 'Rol objetivo',
        stTypeCert: 'Certificación',
        stVerbRewrite: 'Reescribir',
        stVerbReplace: 'Reemplazar',
        stVerbAdd: 'Agregar',
        stEmptyTitle: 'Aún no hay currículum para asesorar',
        stEmptyDesc: 'Sube un currículum primero — el studio te ayudará a mejorarlo línea por línea.',
        stUploadResumeBtn: 'Subir un currículum',
        stLoading: 'Cargando studio…',

        blTitle: 'Crear Currículum US',
        blTemplate: 'Plantilla',
        blTemplateHybrid: 'Híbrido',
        blTemplateChrono: 'Cronológico',
        blTemplateSkillsFirst: 'Habilidades primero',
        blTemplateHybridDesc: 'Habilidades + cronológico — mejor para inmigrantes',
        blTemplateChronoDesc: 'Formato US clásico — mejor para carreras estables',
        blTemplateSkillsDesc: 'Funcional — mejor para cambios de carrera / huecos',
        blOutputLang: 'Idioma de salida',
        blGenerate: 'Generar currículum estilo US',
        blRebuild: 'Regenerar',
        blBuilding: 'Generando…',
        blPreviewNote: 'Vista previa abajo. Copia como texto plano para sitios ATS, o descarga .docx para Word.',
        blCopyText: 'Copiar texto',
        blCopyMd: 'Copiar markdown',
        blDownloadDocx: 'Descargar .docx',

        uploadResume: 'Subir Currículum',
        uploadHint: 'PDF, Word o Imagen • Cualquier Idioma',
        analyzeButton: 'Analizar Currículum',
        analyzing: 'Analizando Currículum...',
        analysisComplete: '¡Análisis Completado!',
        originalLanguage: 'Idioma Original',
        skills: 'Habilidades',
        experience: 'Experiencia',
        education: 'Educación',
        usEquivalents: 'Equivalentes en EE. UU. y Recomendaciones',
        degreeEquivalent: 'Equivalente de Título',
        recommendedCerts: 'Certificaciones Recomendadas',
        recommendedJobs: 'Títulos de Trabajo Recomendados',
        suggestions: 'Sugerencias para Empleadores de EE. UU.',
        chatTitle: 'Asistente de Búsqueda de Empleo',
        chatSubtitle: 'Siempre aquí para ayudar',
        chatPlaceholder: 'Pregúntame lo que sea...',
        chatWelcome: '¡Hola! Soy tu asistente de búsqueda de empleo.',
        chatAskCoach: 'Pregunta al coach',

        commonError: 'Algo salió mal. Inténtalo de nuevo.',
        commonCopyBlocked: 'Falló la copia — tu navegador puede haber bloqueado el portapapeles',
    },

    // ========================================================
    // FRENCH (fr)
    // ========================================================
    fr: {
        languageName: 'French',
        title: 'EmployAI',
        subtitle: "Téléchargez votre CV et laissez l'IA trouver votre emploi idéal",

        navHome: 'Accueil',
        navAnalyze: 'Analyser',
        navStudio: 'Studio',
        navResumes: 'CV',
        navJobs: 'Emplois',
        navLogIn: 'Se connecter',
        navSignUp: "S'inscrire",
        navLogOut: 'Se déconnecter',
        navToggleLight: 'Passer au mode clair',
        navToggleDark: 'Passer au mode sombre',

        homeBadge: 'Conçu pour les immigrants · Fonctionne en 6 langues',
        homeHeroTitle: "Le marché du travail ne doit pas être confus dans un nouveau pays.",
        homeHeroSub: "Téléchargez votre CV dans n'importe quelle langue. EmployAI le traduit, vous met en relation avec de vrais emplois américains et vous coache vers de meilleures offres — gratuitement.",
        homeHeroPlaceholder: 'Quel type de travail cherchez-vous ? (ex. backend à distance en fintech)',
        homeCtaUpload: 'Télécharger mon CV — gratuit',
        homeCtaContinue: 'Continuer vers Analyser',
        homeIntentHint: 'Nous utiliserons cela pour orienter vos correspondances.',
        homePopular: 'Populaires :',
        homePop1: 'Ingénieur logiciel',
        homePop2: 'Infirmier(ère) diplômé(e)',
        homePop3: 'Construction',
        homePop4: 'Comptabilité',
        homeTrustNoFee: 'Aucun frais. Pas de carte bancaire.',
        homeTrustPrivate: 'Nous ne vendons jamais vos données',
        homeTrustAnyLang: "Fonctionne dans n'importe quelle langue",

        homeHowLabel: 'Comment ça marche',
        homeHowTitle: 'De votre CV à votre prochain emploi en trois étapes.',
        homeStep1Title: "Téléchargez, dans n'importe quelle langue",
        homeStep1Desc: 'Déposez votre CV — PDF, Word ou même une photo. Nous prenons en charge espagnol, français, arabe, chinois, hindi et anglais. Nous traduisons et structurons automatiquement.',
        homeStep2Title: 'Voyez de vrais emplois correspondants',
        homeStep2Desc: "Nous comparons vos compétences aux offres américaines réelles avec du sens — pas juste des mots-clés — pour qu'un ingénieur paiements en Argentine soit associé à des rôles fintech, pas à des résultats génériques.",
        homeStep3Title: 'Améliorez et postulez',
        homeStep3Desc: "Votre coach IA suggère des modifications spécifiques pour renforcer votre CV face aux employeurs américains — et vous construit une version au format US, prête à télécharger.",

        homeFeaturesLabel: 'Vraie correspondance, pas une soupe de mots-clés',
        homeFeaturesTitle: "Voyez exactement à quel point chaque emploi correspond à votre profil — et pourquoi.",
        homeFeaturesIntro: "La plupart des sites trient par date ou par qui a payé pour être en avant. EmployAI trie par à quel point vos compétences et expérience correspondent vraiment au poste.",
        homeFeatBullet1Bold: 'Scores de correspondance colorés',
        homeFeatBullet1: 'voyez en un coup d\'œil quels emplois valent votre temps.',
        homeFeatBullet2Bold: 'Voyez vos scores monter',
        homeFeatBullet2: 'à mesure que vous acceptez les améliorations.',
        homeFeatBullet3Bold: 'Enregistrez et suivez',
        homeFeatBullet3: "vos candidatures de l'entretien à l'offre.",
        homeFeatTopMatches: 'Meilleures correspondances pour vous',
        homeFeatPreviewNote: 'Aperçu en direct · noté en secondes.',

        homeLangsLabel: 'Les langues que nous parlons',
        homeLangsTitle: "Téléchargez votre CV dans la langue où il a été écrit.",
        homeLangsSub: "Six langues aujourd'hui. D'autres à venir au fur et à mesure que nous entendons les demandeurs d'emploi du monde entier.",

        homeStoriesLabel: 'Témoignages',
        homeStoriesTitle: 'De qualifié — à embauché.',
        homeStoriesFootnote: 'Les témoignages ci-dessus utilisent des portraits factices — de vrais témoignages et photos arrivent.',

        homeFinalTitle: 'Commencez par votre CV. Nous nous occupons du reste.',
        homeFinalSub: 'Gratuit. Disponible en six langues. Rien à installer.',
        homeFinalSeeHow: 'Voir comment ça marche',

        homeFooterDesc: 'Plateforme multilingue de recherche d\'emploi IA pour les immigrants navigant sur le marché du travail américain. Gratuit, privé et humain.',
        homeFooterProduct: 'Produit',
        homeFooterHowItWorks: 'Comment ça marche',
        homeFooterStudio: 'Resume Studio',
        homeFooterMatching: 'Correspondance d\'emplois',
        homeFooterTracking: 'Suivi des candidatures',
        homeFooterAbout: 'À propos',
        homeFooterTeam: "L'équipe",
        homeFooterMission: 'Mission',
        homeFooterPrivacy: 'Confidentialité',
        homeFooterGithub: 'GitHub',
        homeFooterDisclaimer: 'EmployAI — projet de Jericho Senior High School. Ni employeur légal ni service d\'immigration agréé.',

        authWelcomeBack: 'Bon retour',
        authLoginSub: "Connectez-vous pour continuer votre recherche d'emploi",
        authCreateAccount: 'Créez votre compte',
        authSignupSub: 'Enregistrez votre profil et suivez vos candidatures',
        authEmail: 'E-mail',
        authPassword: 'Mot de passe',
        authEmailPh: 'vous@exemple.com',
        authPasswordPh: '••••••••',
        authPasswordCreatePh: 'Au moins 8 caractères',
        authName: 'Nom',
        authNameOptional: '(facultatif)',
        authNamePh: 'Votre nom',
        authLogIn: 'Se connecter',
        authLoggingIn: 'Connexion...',
        authCreate: 'Créer un compte',
        authCreating: 'Création du compte...',
        authPwTooShort: 'Le mot de passe doit comporter au moins 10 caractères',
        authNoAccount: "Vous n'avez pas de compte ?",
        authHaveAccount: 'Vous avez déjà un compte ?',

        anActive: 'Actif',
        anTopMatch: 'meilleure correspondance',
        anJobs: 'emplois',
        anSaved: 'enregistrés',
        anUploadNew: 'Télécharger nouveau',
        anReRun: 'Relancer la recherche',
        anImproveStudio: 'Améliorer dans Studio',
        anBiasingToward: 'Orientation des correspondances vers :',
        anBiasingForward: 'Nous orienterons les correspondances vers :',
        anClearIntent: "Effacer l'intention et réordonner",
        anLowMatchTitleA: 'Votre meilleure correspondance n\'est que ',
        anLowMatchTitleB: '%.',
        anLowMatchSub: "Voulez-vous que l'assistant IA suggère des ajustements spécifiques à votre CV ou des titres alternatifs ?",
        anLowMatchGetTips: 'Recevoir des conseils',
        anLowMatchDismiss: 'Ignorer',

        anMatchedJobs: 'Emplois correspondants',
        anSortBest: 'Meilleure correspondance',
        anSortRecent: 'Plus récents',
        anSortPay: 'Salaire le plus élevé',
        anFilters: 'Filtres :',
        anFilterRemote: 'À distance',
        anFilterFullTime: 'Temps plein',
        anFilter100k: '100k$+',
        anClearAll: 'Tout effacer',
        anNoMatchesForFilters: 'Aucun emploi ne correspond à ces filtres.',
        anClearFilters: 'Effacer les filtres',

        sbYourProfile: 'Votre profil',
        sbTranslatedFrom: 'Traduit du',
        sbSummary: 'Résumé',
        sbTargetRoles: 'Rôles ciblés',
        sbSkills: 'Compétences',
        sbExperience: 'Expérience',
        sbEducation: 'Éducation',
        sbUsEquivalents: 'Équivalents US',
        sbDegree: 'Diplôme',
        sbRecCerts: 'Certifications recommandées',
        sbImproveStudio: 'Améliorer ce CV dans le Studio',

        viewJob: "Voir l'Offre",
        jobMarkApplied: 'Marquer comme postulé',
        jobApplied: 'Postulé',
        jobSave: 'Enregistrer pour plus tard',
        jobUnsave: 'Retirer',
        matchingJobs: 'Emplois correspondants',
        searchingJobs: "Recherche d'emplois...",
        noJobsFound: 'Aucun emploi trouvé.',

        resTitle: 'Vos CV',
        resEmpty: 'Téléchargez votre premier CV pour commencer.',
        resCount: (n) => `${n} enregistrés. L'actif dirige les correspondances et le chat.`,
        resUploadNew: 'Télécharger nouveau',
        resEmptyTitle: 'Pas encore de CV',
        resEmptyDesc: "Téléchargez votre premier CV sur la page Analyser. L'IA traduira, analysera et trouvera des emplois correspondants.",
        resEmptyCta: 'Télécharger votre premier CV',
        resActiveBadge: 'Actif',
        resSetActive: 'Activer',
        resRename: 'Renommer',
        resDelete: 'Supprimer',
        resSaveTip: 'Enregistrer',
        resCancelTip: 'Annuler',
        resUploadedOn: 'Téléchargé',
        resLoading: 'Chargement de vos CV…',
        resConfirmDelete: (label) => `Supprimer "${label}" ? Cela ne peut pas être annulé.`,

        jpTitle: 'Vos emplois',
        jpSub: 'Signets enregistrés et candidatures que vous suivez.',
        jpTabSaved: 'Enregistrés',
        jpTabApps: 'Candidatures',
        jpEmptySaved: "Aucun emploi enregistré pour l'instant",
        jpEmptySavedDesc: 'Cliquez sur le cœur de tout emploi dans vos correspondances pour le sauvegarder.',
        jpFindJobs: 'Trouver des emplois',
        jpEmptyApps: 'Aucune candidature suivie',
        jpEmptyAppsDesc: 'Quand vous postulez à un emploi, cliquez sur « Marquer comme postulé » pour le suivre ici.',
        jpUnsave: 'Retirer',
        jpDelete: 'Supprimer',
        jpDeleteConfirm: 'Supprimer cet enregistrement de candidature ?',
        jpNotes: 'Notes',
        jpNotesPh: 'Entretien mardi, contacté le recruteur, etc.',
        jpAppliedOn: 'Postulé',
        jpLoading: 'Chargement de vos emplois…',
        jpStatusApplied: 'Postulé',
        jpStatusInterviewing: 'En entretien',
        jpStatusOffered: 'Offre reçue',
        jpStatusRejected: 'Refusé',
        jpStatusWithdrawn: 'Retiré',

        stEditing: 'Édition :',
        stManage: 'Gérer',
        stReRankJobs: 'Reclasser les emplois',
        stBuildUsResume: 'Créer un CV US',
        stYourResume: 'Votre CV',
        stAiCoach: 'Coach IA',
        stExplainIn: 'Expliquer en',
        stFocusLabel: 'Sur quoi le coach doit-il se concentrer ?',
        stFocusOptional: '(facultatif)',
        stFocusPh: 'ex. mettre en valeur le leadership, raccourcir les puces',
        stGetSuggestions: 'Obtenir des suggestions',
        stNewSuggestions: 'Nouvelles suggestions',
        stCoaching: 'Coaching…',
        stCoachEmptyA: 'Cliquez sur ',
        stCoachEmptyB: ' pour voir des façons spécifiques de renforcer ce CV.',
        stCurrently: 'Actuellement',
        stSuggested: 'Suggéré',
        stApply: 'Appliquer',
        stSkip: 'Passer',
        stTypeSummary: 'Résumé',
        stTypeBullet: "Puce d'expérience",
        stTypeSkill: 'Compétence',
        stTypeNewSkill: 'Nouvelle compétence',
        stTypeTargetRole: 'Rôle ciblé',
        stTypeCert: 'Certification',
        stVerbRewrite: 'Réécrire',
        stVerbReplace: 'Remplacer',
        stVerbAdd: 'Ajouter',
        stEmptyTitle: 'Pas encore de CV à coacher',
        stEmptyDesc: "Téléchargez un CV d'abord — le studio vous aidera à l'améliorer ligne par ligne.",
        stUploadResumeBtn: 'Télécharger un CV',
        stLoading: 'Chargement du studio…',

        blTitle: 'Créer un CV US',
        blTemplate: 'Modèle',
        blTemplateHybrid: 'Hybride',
        blTemplateChrono: 'Chronologique',
        blTemplateSkillsFirst: "Compétences d'abord",
        blTemplateHybridDesc: 'Compétences + chronologique — idéal pour les immigrants',
        blTemplateChronoDesc: 'Format US classique — idéal pour carrières stables',
        blTemplateSkillsDesc: "Fonctionnel — idéal pour reconversions / trous",
        blOutputLang: 'Langue de sortie',
        blGenerate: 'Générer un CV adapté US',
        blRebuild: 'Régénérer',
        blBuilding: 'Génération…',
        blPreviewNote: 'Aperçu ci-dessous. Copiez en texte brut pour ATS, ou téléchargez .docx pour Word.',
        blCopyText: 'Copier le texte',
        blCopyMd: 'Copier markdown',
        blDownloadDocx: 'Télécharger .docx',

        uploadResume: 'Télécharger le CV',
        uploadHint: 'PDF, Word ou Image • Toute Langue',
        analyzeButton: 'Analyser le CV',
        analyzing: 'Analyse du CV...',
        analysisComplete: 'Analyse Terminée !',
        originalLanguage: 'Langue Originale',
        skills: 'Compétences',
        experience: 'Expérience',
        education: 'Éducation',
        usEquivalents: 'Équivalents US et Recommandations',
        degreeEquivalent: 'Équivalent du Diplôme',
        recommendedCerts: 'Certifications Recommandées',
        recommendedJobs: 'Titres de Postes Recommandés',
        suggestions: 'Suggestions pour les Employeurs US',
        chatTitle: "Assistant Recherche d'Emploi",
        chatSubtitle: 'Toujours là pour vous aider',
        chatPlaceholder: 'Posez-moi une question...',
        chatWelcome: "Bonjour ! Je suis votre assistant de recherche d'emploi.",
        chatAskCoach: 'Demander au coach',

        commonError: "Quelque chose a mal tourné. Veuillez réessayer.",
        commonCopyBlocked: "La copie a échoué — votre navigateur peut avoir bloqué l'accès au presse-papiers",
    },

    // ========================================================
    // ARABIC (ar) — RTL
    // ========================================================
    ar: {
        languageName: 'Arabic',
        title: 'EmployAI',
        subtitle: 'ارفع سيرتك الذاتية ودع الذكاء الاصطناعي يجد لك الوظيفة المثالية',

        navHome: 'الرئيسية',
        navAnalyze: 'تحليل',
        navStudio: 'استوديو',
        navResumes: 'السير الذاتية',
        navJobs: 'الوظائف',
        navLogIn: 'تسجيل الدخول',
        navSignUp: 'إنشاء حساب',
        navLogOut: 'تسجيل الخروج',
        navToggleLight: 'التبديل إلى الوضع الفاتح',
        navToggleDark: 'التبديل إلى الوضع الداكن',

        homeBadge: 'مصمم للمهاجرين · يعمل بـ 6 لغات',
        homeHeroTitle: 'سوق العمل ليس مضطراً للارتباك في بلد جديد.',
        homeHeroSub: 'ارفع سيرتك الذاتية بأي لغة. EmployAI يترجمها، يطابقك مع وظائف حقيقية في الولايات المتحدة، ويوجهك نحو عروض أفضل — مجاناً.',
        homeHeroPlaceholder: 'ما نوع العمل الذي تبحث عنه؟ (مثل وظائف خلفية عن بُعد في التكنولوجيا المالية)',
        homeCtaUpload: 'رفع سيرتي الذاتية — مجاناً',
        homeCtaContinue: 'متابعة إلى التحليل',
        homeIntentHint: 'سنستخدم ذلك لتوجيه نتائج الوظائف المتطابقة.',
        homePopular: 'شائع:',
        homePop1: 'مهندس برمجيات',
        homePop2: 'ممرض مسجل',
        homePop3: 'بناء',
        homePop4: 'محاسبة',
        homeTrustNoFee: 'بدون رسوم. بدون بطاقة ائتمان.',
        homeTrustPrivate: 'لا نبيع بياناتك أبدًا',
        homeTrustAnyLang: 'يعمل بأي لغة',

        homeHowLabel: 'كيف يعمل',
        homeHowTitle: 'من سيرتك الذاتية إلى وظيفتك التالية في ثلاث خطوات.',
        homeStep1Title: 'ارفع، بأي لغة',
        homeStep1Desc: 'أسقط سيرتك الذاتية — PDF أو Word أو حتى صورة. ندعم الإسبانية والفرنسية والعربية والصينية والهندية والإنجليزية. نترجم ونُهيكل تلقائياً.',
        homeStep2Title: 'شاهد وظائف حقيقية متطابقة',
        homeStep2Desc: 'نقارن مهاراتك بإعلانات الوظائف الأمريكية الحية باستخدام المعنى — وليس فقط الكلمات المفتاحية — لذا يتم مطابقة مهندس معالجة المدفوعات في الأرجنتين مع أدوار التكنولوجيا المالية، وليس نتائج "مهندس" عامة.',
        homeStep3Title: 'حسّن وتقدم',
        homeStep3Desc: 'مدربك بالذكاء الاصطناعي يقترح تعديلات محددة لتقوية سيرتك الذاتية لأصحاب العمل في الولايات المتحدة — ويبني لك نسخة بتنسيق أمريكي صحيح، جاهزة للتنزيل.',

        homeFeaturesLabel: 'مطابقة حقيقية، وليس حساء كلمات مفتاحية',
        homeFeaturesTitle: 'شاهد بالضبط مدى ملاءمة كل وظيفة لخلفيتك — ولماذا.',
        homeFeaturesIntro: 'معظم مواقع الوظائف تُرتب حسب حداثة الإعلان، أو حسب من دفع أكثر للإبراز. EmployAI يُرتب حسب مدى تطابق مهاراتك وخبرتك فعلاً مع الدور.',
        homeFeatBullet1Bold: 'درجات مطابقة ملونة',
        homeFeatBullet1: 'شاهد أي وظائف تستحق وقتك بنظرة واحدة.',
        homeFeatBullet2Bold: 'شاهد الدرجات ترتفع',
        homeFeatBullet2: 'بينما تقبل تحسينات السيرة الذاتية.',
        homeFeatBullet3Bold: 'احفظ وتتبع',
        homeFeatBullet3: 'الطلبات من المقابلة إلى العرض.',
        homeFeatTopMatches: 'أفضل التطابقات لك',
        homeFeatPreviewNote: 'معاينة مباشرة · تم تقييمها في ثوانٍ.',

        homeLangsLabel: 'اللغات التي نتحدثها',
        homeLangsTitle: 'ارفع سيرتك الذاتية باللغة التي كُتبت بها.',
        homeLangsSub: 'ست لغات اليوم. المزيد قادمة بينما نسمع من الباحثين عن عمل حول العالم.',

        homeStoriesLabel: 'قصص',
        homeStoriesTitle: 'من مؤهل — إلى موظف.',
        homeStoriesFootnote: 'القصص أعلاه تستخدم صوراً نائبة — شهادات حقيقية وصور قادمة.',

        homeFinalTitle: 'ابدأ بسيرتك الذاتية. سنتولى الباقي.',
        homeFinalSub: 'مجاني. متاح بست لغات. لا شيء للتثبيت.',
        homeFinalSeeHow: 'انظر كيف يعمل',

        homeFooterDesc: 'منصة بحث عن وظائف بالذكاء الاصطناعي متعددة اللغات مبنية للمهاجرين الذين يبحرون في سوق العمل الأمريكي. مجاني، خاص، وودود.',
        homeFooterProduct: 'المنتج',
        homeFooterHowItWorks: 'كيف يعمل',
        homeFooterStudio: 'استوديو السيرة الذاتية',
        homeFooterMatching: 'مطابقة الوظائف',
        homeFooterTracking: 'تتبع الطلبات',
        homeFooterAbout: 'من نحن',
        homeFooterTeam: 'الفريق',
        homeFooterMission: 'المهمة',
        homeFooterPrivacy: 'الخصوصية',
        homeFooterGithub: 'GitHub',
        homeFooterDisclaimer: 'EmployAI — مشروع مدرسة Jericho الثانوية. ليس صاحب عمل قانوني ولا خدمة هجرة مرخصة.',

        authWelcomeBack: 'مرحباً بعودتك',
        authLoginSub: 'سجل الدخول لمواصلة البحث عن وظيفة',
        authCreateAccount: 'أنشئ حسابك',
        authSignupSub: 'احفظ ملفك الشخصي وتتبع طلباتك',
        authEmail: 'البريد الإلكتروني',
        authPassword: 'كلمة المرور',
        authEmailPh: 'you@example.com',
        authPasswordPh: '••••••••',
        authPasswordCreatePh: '8 أحرف على الأقل',
        authName: 'الاسم',
        authNameOptional: '(اختياري)',
        authNamePh: 'اسمك',
        authLogIn: 'تسجيل الدخول',
        authLoggingIn: 'جاري تسجيل الدخول...',
        authCreate: 'إنشاء حساب',
        authCreating: 'جاري إنشاء الحساب...',
        authPwTooShort: 'كلمة المرور يجب أن تكون 10 أحرف على الأقل',
        authNoAccount: 'ليس لديك حساب؟',
        authHaveAccount: 'لديك حساب بالفعل؟',

        anActive: 'نشط',
        anTopMatch: 'أفضل تطابق',
        anJobs: 'وظائف',
        anSaved: 'محفوظة',
        anUploadNew: 'رفع جديد',
        anReRun: 'إعادة البحث',
        anImproveStudio: 'حسّن في الاستوديو',
        anBiasingToward: 'توجيه التطابقات نحو:',
        anBiasingForward: 'سنوجه التطابقات نحو:',
        anClearIntent: 'مسح النية وإعادة الترتيب',
        anLowMatchTitleA: 'أفضل تطابق لك هو فقط ',
        anLowMatchTitleB: '%.',
        anLowMatchSub: 'هل تريد من المساعد الذكي اقتراح تعديلات محددة لسيرتك الذاتية أو عناوين وظائف بديلة؟',
        anLowMatchGetTips: 'احصل على نصائح',
        anLowMatchDismiss: 'تجاهل',

        anMatchedJobs: 'الوظائف المتطابقة',
        anSortBest: 'أفضل تطابق',
        anSortRecent: 'الأحدث',
        anSortPay: 'أعلى راتب',
        anFilters: 'المرشحات:',
        anFilterRemote: 'عن بُعد',
        anFilterFullTime: 'دوام كامل',
        anFilter100k: '+100 ألف دولار',
        anClearAll: 'مسح الكل',
        anNoMatchesForFilters: 'لا توجد وظائف تطابق هذه المرشحات.',
        anClearFilters: 'مسح المرشحات',

        sbYourProfile: 'ملفك الشخصي',
        sbTranslatedFrom: 'مترجم من',
        sbSummary: 'ملخص',
        sbTargetRoles: 'الأدوار المستهدفة',
        sbSkills: 'المهارات',
        sbExperience: 'الخبرة',
        sbEducation: 'التعليم',
        sbUsEquivalents: 'المعادلات الأمريكية',
        sbDegree: 'الشهادة',
        sbRecCerts: 'الشهادات الموصى بها',
        sbImproveStudio: 'حسّن هذه السيرة في الاستوديو',

        viewJob: 'عرض الوظيفة',
        jobMarkApplied: 'وضع علامة كمتقدم',
        jobApplied: 'متقدم',
        jobSave: 'احفظ لوقت لاحق',
        jobUnsave: 'إلغاء الحفظ',
        matchingJobs: 'وظائف مطابقة لك',
        searchingJobs: 'جاري البحث عن وظائف...',
        noJobsFound: 'لم يتم العثور على وظائف.',

        resTitle: 'سيرك الذاتية',
        resEmpty: 'ارفع سيرتك الذاتية الأولى للبدء.',
        resCount: (n) => `${n} محفوظة. النشطة توجه التطابقات والمحادثة.`,
        resUploadNew: 'رفع جديد',
        resEmptyTitle: 'لا توجد سير ذاتية بعد',
        resEmptyDesc: 'ارفع سيرتك الذاتية الأولى في صفحة التحليل. سيقوم الذكاء الاصطناعي بالترجمة والتحليل وإيجاد الوظائف المطابقة.',
        resEmptyCta: 'ارفع سيرتك الذاتية الأولى',
        resActiveBadge: 'نشط',
        resSetActive: 'تعيين كنشط',
        resRename: 'إعادة تسمية',
        resDelete: 'حذف',
        resSaveTip: 'حفظ',
        resCancelTip: 'إلغاء',
        resUploadedOn: 'تم الرفع',
        resLoading: 'جاري تحميل سيرك الذاتية…',
        resConfirmDelete: (label) => `حذف "${label}"؟ لا يمكن التراجع عن هذا.`,

        jpTitle: 'وظائفك',
        jpSub: 'الإشارات المرجعية المحفوظة والطلبات التي تتتبعها.',
        jpTabSaved: 'محفوظة',
        jpTabApps: 'الطلبات',
        jpEmptySaved: 'لا توجد وظائف محفوظة بعد',
        jpEmptySavedDesc: 'انقر على القلب لأي وظيفة في تطابقاتك لحفظها لاحقاً.',
        jpFindJobs: 'البحث عن وظائف',
        jpEmptyApps: 'لا توجد طلبات متتبعة بعد',
        jpEmptyAppsDesc: 'عندما تتقدم لوظيفة، انقر على "وضع علامة كمتقدم" لتتبع حالتها هنا.',
        jpUnsave: 'إلغاء الحفظ',
        jpDelete: 'حذف',
        jpDeleteConfirm: 'حذف سجل هذا الطلب؟',
        jpNotes: 'ملاحظات',
        jpNotesPh: 'مقابلة الثلاثاء، تواصلت مع المسؤول، إلخ.',
        jpAppliedOn: 'تقدمت',
        jpLoading: 'جاري تحميل وظائفك…',
        jpStatusApplied: 'تقدمت',
        jpStatusInterviewing: 'في مقابلة',
        jpStatusOffered: 'تم العرض',
        jpStatusRejected: 'مرفوض',
        jpStatusWithdrawn: 'منسحب',

        stEditing: 'تحرير:',
        stManage: 'إدارة',
        stReRankJobs: 'إعادة ترتيب الوظائف',
        stBuildUsResume: 'بناء سيرة أمريكية',
        stYourResume: 'سيرتك الذاتية',
        stAiCoach: 'مدرب الذكاء الاصطناعي',
        stExplainIn: 'اشرح بـ',
        stFocusLabel: 'على ماذا يجب أن يركز المدرب؟',
        stFocusOptional: '(اختياري)',
        stFocusPh: 'مثال: التأكيد على القيادة، تقصير النقاط',
        stGetSuggestions: 'احصل على اقتراحات',
        stNewSuggestions: 'اقتراحات جديدة',
        stCoaching: 'جاري التدريب…',
        stCoachEmptyA: 'انقر على ',
        stCoachEmptyB: ' لرؤية طرق محددة لتقوية هذه السيرة الذاتية.',
        stCurrently: 'حالياً',
        stSuggested: 'مقترح',
        stApply: 'تطبيق',
        stSkip: 'تخطي',
        stTypeSummary: 'ملخص',
        stTypeBullet: 'نقطة خبرة',
        stTypeSkill: 'مهارة',
        stTypeNewSkill: 'مهارة جديدة',
        stTypeTargetRole: 'دور مستهدف',
        stTypeCert: 'شهادة',
        stVerbRewrite: 'إعادة كتابة',
        stVerbReplace: 'استبدال',
        stVerbAdd: 'إضافة',
        stEmptyTitle: 'لا توجد سيرة لتدريبها بعد',
        stEmptyDesc: 'ارفع سيرة ذاتية أولاً — الاستوديو سيساعدك على تحسينها سطراً بسطر.',
        stUploadResumeBtn: 'ارفع سيرة ذاتية',
        stLoading: 'جاري تحميل الاستوديو…',

        blTitle: 'بناء سيرة أمريكية',
        blTemplate: 'قالب',
        blTemplateHybrid: 'هجين',
        blTemplateChrono: 'زمني',
        blTemplateSkillsFirst: 'المهارات أولاً',
        blTemplateHybridDesc: 'مهارات + زمني — الأفضل للمهاجرين',
        blTemplateChronoDesc: 'تنسيق أمريكي كلاسيكي — الأفضل للمسيرات الثابتة',
        blTemplateSkillsDesc: 'وظيفي — الأفضل لمن يغيرون مسيرتهم / فجوات',
        blOutputLang: 'لغة الإخراج',
        blGenerate: 'إنشاء سيرة بتنسيق أمريكي',
        blRebuild: 'إعادة الإنشاء',
        blBuilding: 'جاري الإنشاء…',
        blPreviewNote: 'المعاينة أدناه. انسخ كنص عادي لمواقع ATS، أو حمّل .docx لـ Word.',
        blCopyText: 'نسخ النص',
        blCopyMd: 'نسخ Markdown',
        blDownloadDocx: 'تنزيل .docx',

        uploadResume: 'تحميل السيرة الذاتية',
        uploadHint: 'PDF أو Word أو صورة • أي لغة',
        analyzeButton: 'تحليل السيرة الذاتية',
        analyzing: 'جاري تحليل السيرة الذاتية...',
        analysisComplete: 'اكتمل التحليل!',
        originalLanguage: 'اللغة الأصلية',
        skills: 'المهارات',
        experience: 'الخبرة',
        education: 'التعليم',
        usEquivalents: 'المعادلات والتوصيات في الولايات المتحدة',
        degreeEquivalent: 'معادل الشهادة',
        recommendedCerts: 'الشهادات الموصى بها',
        recommendedJobs: 'المسميات الوظيفية الموصى بها',
        suggestions: 'اقتراحات لأصحاب العمل في الولايات المتحدة',
        chatTitle: 'مساعد البحث عن وظيفة',
        chatSubtitle: 'هنا للمساعدة دائماً',
        chatPlaceholder: 'اسألني عن أي شيء...',
        chatWelcome: 'مرحباً! أنا مساعدك في البحث عن وظيفة.',
        chatAskCoach: 'اسأل المدرب',

        commonError: 'حدث خطأ ما. يرجى المحاولة مرة أخرى.',
        commonCopyBlocked: 'فشل النسخ — قد يكون متصفحك قد حظر الوصول إلى الحافظة',
    },

    // ========================================================
    // CHINESE (zh)
    // ========================================================
    zh: {
        languageName: 'Chinese',
        title: 'EmployAI',
        subtitle: '上传您的简历，让人工智能为您找到完美的工作',

        navHome: '主页',
        navAnalyze: '分析',
        navStudio: '工作室',
        navResumes: '简历',
        navJobs: '工作',
        navLogIn: '登录',
        navSignUp: '注册',
        navLogOut: '退出登录',
        navToggleLight: '切换到浅色模式',
        navToggleDark: '切换到深色模式',

        homeBadge: '为移民设计 · 支持6种语言',
        homeHeroTitle: '在新国家求职市场不必让人困惑。',
        homeHeroSub: '用任何语言上传您的简历。EmployAI 翻译它，将您与真实的美国工作匹配，并指导您获得更好的工作机会 — 免费的。',
        homeHeroPlaceholder: '您在寻找什么类型的工作？（例如金融科技远程后端职位）',
        homeCtaUpload: '上传我的简历 — 免费',
        homeCtaContinue: '继续到分析',
        homeIntentHint: '我们将用它来调整您的工作匹配。',
        homePopular: '热门:',
        homePop1: '软件工程师',
        homePop2: '注册护士',
        homePop3: '建筑',
        homePop4: '会计',
        homeTrustNoFee: '无费用。无信用卡。',
        homeTrustPrivate: '我们绝不出售您的数据',
        homeTrustAnyLang: '支持任何语言',

        homeHowLabel: '工作原理',
        homeHowTitle: '从您的简历到下一份工作，三步搞定。',
        homeStep1Title: '用任何语言上传',
        homeStep1Desc: '拖入您的简历 — PDF、Word 或照片均可。我们支持西班牙语、法语、阿拉伯语、中文、印地语和英语。我们自动翻译和结构化。',
        homeStep2Title: '查看真实匹配工作',
        homeStep2Desc: '我们用含义而非仅关键词将您的技能与实时美国职位列表进行比较 — 所以阿根廷的支付处理工程师会匹配到金融科技职位，而不是通用的"工程师"结果。',
        homeStep3Title: '改进并申请',
        homeStep3Desc: '您的AI教练建议具体修改，使您的简历对美国雇主更具吸引力 — 并为您构建格式正确的美国版本，可供下载。',

        homeFeaturesLabel: '真正的匹配，而非关键词堆砌',
        homeFeaturesTitle: '准确看到每份工作与您的背景匹配程度 — 以及原因。',
        homeFeaturesIntro: '大多数求职网站按发布时间或雇主付费推广排序。EmployAI 按您的技能和经验实际匹配工作的程度排序。',
        homeFeatBullet1Bold: '彩色编码的匹配分数',
        homeFeatBullet1: '一目了然地看到哪些工作值得您花时间。',
        homeFeatBullet2Bold: '观察分数上升',
        homeFeatBullet2: '当您接受简历改进时。',
        homeFeatBullet3Bold: '保存和跟踪',
        homeFeatBullet3: '从面试到录用的申请。',
        homeFeatTopMatches: '最佳匹配',
        homeFeatPreviewNote: '实时预览 · 几秒钟评分。',

        homeLangsLabel: '我们支持的语言',
        homeLangsTitle: '用您简历的原始语言上传。',
        homeLangsSub: '今天六种语言。随着我们听到世界各地求职者的声音，更多即将推出。',

        homeStoriesLabel: '故事',
        homeStoriesTitle: '从合格 — 到被录用。',
        homeStoriesFootnote: '上述故事使用占位肖像 — 真实推荐和照片即将到来。',

        homeFinalTitle: '从您的简历开始。我们处理其余的事情。',
        homeFinalSub: '免费使用。六种语言可用。无需安装。',
        homeFinalSeeHow: '查看工作原理',

        homeFooterDesc: '为驾驭美国劳动力市场的移民打造的多语言人工智能求职平台。免费、私密、人性化。',
        homeFooterProduct: '产品',
        homeFooterHowItWorks: '工作原理',
        homeFooterStudio: '简历工作室',
        homeFooterMatching: '工作匹配',
        homeFooterTracking: '申请跟踪',
        homeFooterAbout: '关于',
        homeFooterTeam: '团队',
        homeFooterMission: '使命',
        homeFooterPrivacy: '隐私',
        homeFooterGithub: 'GitHub',
        homeFooterDisclaimer: 'EmployAI — Jericho Senior High School 项目。非法律雇主或持牌移民服务。',

        authWelcomeBack: '欢迎回来',
        authLoginSub: '登录以继续您的求职',
        authCreateAccount: '创建您的账户',
        authSignupSub: '保存您的资料并跟踪您的申请',
        authEmail: '电子邮箱',
        authPassword: '密码',
        authEmailPh: 'you@example.com',
        authPasswordPh: '••••••••',
        authPasswordCreatePh: '至少8个字符',
        authName: '姓名',
        authNameOptional: '（可选）',
        authNamePh: '您的姓名',
        authLogIn: '登录',
        authLoggingIn: '登录中...',
        authCreate: '创建账户',
        authCreating: '创建账户中...',
        authPwTooShort: '密码必须至少为10个字符',
        authNoAccount: '没有账户？',
        authHaveAccount: '已有账户？',

        anActive: '活动',
        anTopMatch: '最佳匹配',
        anJobs: '工作',
        anSaved: '已保存',
        anUploadNew: '上传新的',
        anReRun: '重新搜索',
        anImproveStudio: '在工作室中改进',
        anBiasingToward: '调整匹配偏向：',
        anBiasingForward: '我们将调整匹配偏向：',
        anClearIntent: '清除意图并重新排序',
        anLowMatchTitleA: '您的最佳匹配只有 ',
        anLowMatchTitleB: '%。',
        anLowMatchSub: '想让AI助手建议具体的简历调整或替代职位吗？',
        anLowMatchGetTips: '获取提示',
        anLowMatchDismiss: '关闭',

        anMatchedJobs: '匹配的工作',
        anSortBest: '最佳匹配',
        anSortRecent: '最新',
        anSortPay: '最高薪水',
        anFilters: '筛选：',
        anFilterRemote: '远程',
        anFilterFullTime: '全职',
        anFilter100k: '10万美元以上',
        anClearAll: '全部清除',
        anNoMatchesForFilters: '没有工作匹配这些筛选条件。',
        anClearFilters: '清除筛选',

        sbYourProfile: '您的资料',
        sbTranslatedFrom: '翻译自',
        sbSummary: '摘要',
        sbTargetRoles: '目标职位',
        sbSkills: '技能',
        sbExperience: '经验',
        sbEducation: '教育',
        sbUsEquivalents: '美国等同',
        sbDegree: '学位',
        sbRecCerts: '推荐证书',
        sbImproveStudio: '在工作室中改进此简历',

        viewJob: '查看职位',
        jobMarkApplied: '标记为已申请',
        jobApplied: '已申请',
        jobSave: '保存以备稍后查看',
        jobUnsave: '取消保存',
        matchingJobs: '为您匹配的职位',
        searchingJobs: '正在搜索职位...',
        noJobsFound: '未找到职位。',

        resTitle: '您的简历',
        resEmpty: '上传您的第一份简历开始使用。',
        resCount: (n) => `已保存 ${n} 份。活动简历驱动工作匹配和聊天。`,
        resUploadNew: '上传新的',
        resEmptyTitle: '尚无简历',
        resEmptyDesc: '在分析页面上传您的第一份简历。AI 将翻译、解析并找到匹配的工作。',
        resEmptyCta: '上传您的第一份简历',
        resActiveBadge: '活动',
        resSetActive: '设为活动',
        resRename: '重命名',
        resDelete: '删除',
        resSaveTip: '保存',
        resCancelTip: '取消',
        resUploadedOn: '上传于',
        resLoading: '正在加载您的简历…',
        resConfirmDelete: (label) => `删除"${label}"？此操作无法撤销。`,

        jpTitle: '您的工作',
        jpSub: '您正在跟踪的保存书签和申请。',
        jpTabSaved: '已保存',
        jpTabApps: '申请',
        jpEmptySaved: '尚无保存的工作',
        jpEmptySavedDesc: '点击匹配工作上的心形图标以保存。',
        jpFindJobs: '查找工作',
        jpEmptyApps: '尚无跟踪的申请',
        jpEmptyAppsDesc: '申请工作时，点击"标记为已申请"以在此跟踪其状态。',
        jpUnsave: '取消保存',
        jpDelete: '删除',
        jpDeleteConfirm: '删除此申请记录？',
        jpNotes: '备注',
        jpNotesPh: '周二面试，联系了招聘人员等。',
        jpAppliedOn: '申请于',
        jpLoading: '正在加载您的工作…',
        jpStatusApplied: '已申请',
        jpStatusInterviewing: '面试中',
        jpStatusOffered: '已录用',
        jpStatusRejected: '已拒绝',
        jpStatusWithdrawn: '已撤回',

        stEditing: '编辑：',
        stManage: '管理',
        stReRankJobs: '重新排序工作',
        stBuildUsResume: '构建美国简历',
        stYourResume: '您的简历',
        stAiCoach: 'AI 教练',
        stExplainIn: '解释语言',
        stFocusLabel: '教练应该专注于什么？',
        stFocusOptional: '（可选）',
        stFocusPh: '例如：强调领导能力，缩短要点',
        stGetSuggestions: '获取建议',
        stNewSuggestions: '新建议',
        stCoaching: '辅导中…',
        stCoachEmptyA: '点击 ',
        stCoachEmptyB: ' 查看加强此简历的具体方法。',
        stCurrently: '当前',
        stSuggested: '建议',
        stApply: '应用',
        stSkip: '跳过',
        stTypeSummary: '摘要',
        stTypeBullet: '经验要点',
        stTypeSkill: '技能',
        stTypeNewSkill: '新技能',
        stTypeTargetRole: '目标职位',
        stTypeCert: '证书',
        stVerbRewrite: '改写',
        stVerbReplace: '替换',
        stVerbAdd: '添加',
        stEmptyTitle: '尚无简历可辅导',
        stEmptyDesc: '先上传一份简历 — 工作室将帮助您逐行改进。',
        stUploadResumeBtn: '上传简历',
        stLoading: '正在加载工作室…',

        blTitle: '构建美国简历',
        blTemplate: '模板',
        blTemplateHybrid: '混合型',
        blTemplateChrono: '时间顺序型',
        blTemplateSkillsFirst: '技能优先型',
        blTemplateHybridDesc: '技能引导+时间顺序 — 最适合移民',
        blTemplateChronoDesc: '经典美式格式 — 最适合稳定的职业生涯',
        blTemplateSkillsDesc: '功能型 — 最适合职业转换/有空白期',
        blOutputLang: '输出语言',
        blGenerate: '生成美式简历',
        blRebuild: '重新生成',
        blBuilding: '生成中…',
        blPreviewNote: '下方预览。复制为纯文本用于 ATS 站点，或下载 .docx 用于 Word。',
        blCopyText: '复制文本',
        blCopyMd: '复制 Markdown',
        blDownloadDocx: '下载 .docx',

        uploadResume: '上传简历',
        uploadHint: 'PDF、Word 或图片 • 任何语言',
        analyzeButton: '分析简历',
        analyzing: '正在分析简历...',
        analysisComplete: '分析完成！',
        originalLanguage: '原始语言',
        skills: '技能',
        experience: '工作经验',
        education: '教育背景',
        usEquivalents: '美国学历认证与建议',
        degreeEquivalent: '学位等效',
        recommendedCerts: '推荐证书',
        recommendedJobs: '推荐职位名称',
        suggestions: '对美国雇主的建议',
        chatTitle: '求职助手',
        chatSubtitle: '随时为您提供帮助',
        chatPlaceholder: '问我任何问题...',
        chatWelcome: '您好！我是您的求职助手。',
        chatAskCoach: '咨询教练',

        commonError: '出错了。请再试一次。',
        commonCopyBlocked: '复制失败 — 您的浏览器可能阻止了剪贴板访问',
    },

    // ========================================================
    // HINDI (hi)
    // ========================================================
    hi: {
        languageName: 'Hindi',
        title: 'EmployAI',
        subtitle: 'अपना रिज्यूमे अपलोड करें और AI को आपके लिए सही जॉब खोजने दें',

        navHome: 'होम',
        navAnalyze: 'विश्लेषण',
        navStudio: 'स्टूडियो',
        navResumes: 'रिज्यूमे',
        navJobs: 'नौकरियां',
        navLogIn: 'लॉग इन',
        navSignUp: 'साइन अप',
        navLogOut: 'लॉग आउट',
        navToggleLight: 'लाइट मोड पर स्विच करें',
        navToggleDark: 'डार्क मोड पर स्विच करें',

        homeBadge: 'अप्रवासियों के लिए बनाया गया · 6 भाषाओं में काम करता है',
        homeHeroTitle: 'नए देश में नौकरी बाजार को भ्रमित होना जरूरी नहीं है।',
        homeHeroSub: 'अपना रिज्यूमे किसी भी भाषा में अपलोड करें। EmployAI इसका अनुवाद करता है, वास्तविक US नौकरियों से आपका मिलान करता है, और बेहतर ऑफर्स की ओर मार्गदर्शन करता है — मुफ्त।',
        homeHeroPlaceholder: 'आप किस प्रकार के काम की तलाश में हैं? (जैसे फिनटेक में रिमोट बैकएंड भूमिकाएं)',
        homeCtaUpload: 'मेरा रिज्यूमे अपलोड करें — मुफ्त',
        homeCtaContinue: 'विश्लेषण पर जाएं',
        homeIntentHint: 'हम इसका उपयोग आपके जॉब मैचों को निर्देशित करने के लिए करेंगे।',
        homePopular: 'लोकप्रिय:',
        homePop1: 'सॉफ्टवेयर इंजीनियर',
        homePop2: 'पंजीकृत नर्स',
        homePop3: 'निर्माण',
        homePop4: 'लेखांकन',
        homeTrustNoFee: 'कोई शुल्क नहीं। कोई क्रेडिट कार्ड नहीं।',
        homeTrustPrivate: 'हम आपका डेटा कभी नहीं बेचते',
        homeTrustAnyLang: 'किसी भी भाषा में काम करता है',

        homeHowLabel: 'यह कैसे काम करता है',
        homeHowTitle: 'आपके रिज्यूमे से आपकी अगली नौकरी तक तीन चरणों में।',
        homeStep1Title: 'किसी भी भाषा में अपलोड करें',
        homeStep1Desc: 'अपना रिज्यूमे ड्रॉप करें — PDF, Word, या यहां तक कि एक तस्वीर। हम स्पेनिश, फ्रेंच, अरबी, चीनी, हिंदी और अंग्रेजी का समर्थन करते हैं। हम स्वचालित रूप से अनुवाद और संरचना करते हैं।',
        homeStep2Title: 'वास्तविक मिलान वाली नौकरियां देखें',
        homeStep2Desc: 'हम आपके कौशल की तुलना अर्थ का उपयोग करके लाइव US जॉब लिस्टिंग से करते हैं — केवल कीवर्ड नहीं — तो अर्जेंटीना में पेमेंट प्रोसेसिंग इंजीनियर सामान्य "इंजीनियर" परिणामों के बजाय फिनटेक भूमिकाओं से मेल खाता है।',
        homeStep3Title: 'सुधारें और आवेदन करें',
        homeStep3Desc: 'आपका AI कोच US नियोक्ताओं के लिए आपके रिज्यूमे को मजबूत बनाने के लिए विशिष्ट संपादन सुझाता है — और आपके लिए ठीक से स्वरूपित US संस्करण बनाता है, डाउनलोड के लिए तैयार।',

        homeFeaturesLabel: 'वास्तविक मिलान, कीवर्ड सूप नहीं',
        homeFeaturesTitle: 'देखें कि प्रत्येक नौकरी आपकी पृष्ठभूमि के साथ कितनी अच्छी तरह फिट बैठती है — और क्यों।',
        homeFeaturesIntro: 'अधिकांश जॉब साइट्स पोस्ट होने की तारीख के अनुसार या नियोक्ता के भुगतान के अनुसार रैंक करती हैं। EmployAI रैंक करता है कि आपके कौशल और अनुभव वास्तव में भूमिका से कितनी अच्छी तरह मेल खाते हैं।',
        homeFeatBullet1Bold: 'रंग-कोडित मिलान स्कोर',
        homeFeatBullet1: 'एक नज़र में देखें कि कौन सी नौकरियां आपके समय के लायक हैं।',
        homeFeatBullet2Bold: 'स्कोर बढ़ते देखें',
        homeFeatBullet2: 'जैसे ही आप रिज्यूमे सुधार स्वीकार करते हैं।',
        homeFeatBullet3Bold: 'सहेजें और ट्रैक करें',
        homeFeatBullet3: 'साक्षात्कार से ऑफर तक आवेदन।',
        homeFeatTopMatches: 'आपके लिए शीर्ष मिलान',
        homeFeatPreviewNote: 'लाइव पूर्वावलोकन · सेकंडों में स्कोर किया गया।',

        homeLangsLabel: 'हम जो भाषाएं बोलते हैं',
        homeLangsTitle: 'अपना रिज्यूमे उस भाषा में अपलोड करें जिसमें यह लिखा गया था।',
        homeLangsSub: 'आज छह भाषाएं। दुनिया भर के नौकरी चाहने वालों से सुनकर और भी आ रही हैं।',

        homeStoriesLabel: 'कहानियां',
        homeStoriesTitle: 'योग्य से — नियुक्त तक।',
        homeStoriesFootnote: 'ऊपर की कहानियां प्लेसहोल्डर पोर्ट्रेट का उपयोग करती हैं — वास्तविक प्रशंसापत्र और तस्वीरें आ रही हैं।',

        homeFinalTitle: 'अपने रिज्यूमे से शुरू करें। बाकी हम संभाल लेंगे।',
        homeFinalSub: 'उपयोग करने के लिए मुफ्त। छह भाषाओं में उपलब्ध। कुछ भी इंस्टॉल करने की आवश्यकता नहीं।',
        homeFinalSeeHow: 'देखें यह कैसे काम करता है',

        homeFooterDesc: 'US श्रम बाजार में नेविगेट करने वाले अप्रवासियों के लिए बनाया गया बहुभाषी AI जॉब-सर्च प्लेटफॉर्म। मुफ्त, निजी और मानवीय।',
        homeFooterProduct: 'उत्पाद',
        homeFooterHowItWorks: 'यह कैसे काम करता है',
        homeFooterStudio: 'रिज्यूमे स्टूडियो',
        homeFooterMatching: 'जॉब मैचिंग',
        homeFooterTracking: 'आवेदन ट्रैकिंग',
        homeFooterAbout: 'हमारे बारे में',
        homeFooterTeam: 'टीम',
        homeFooterMission: 'मिशन',
        homeFooterPrivacy: 'गोपनीयता',
        homeFooterGithub: 'GitHub',
        homeFooterDisclaimer: 'EmployAI — Jericho Senior High School परियोजना। कानूनी नियोक्ता या लाइसेंस प्राप्त आव्रजन सेवा नहीं।',

        authWelcomeBack: 'वापस स्वागत है',
        authLoginSub: 'अपनी जॉब सर्च जारी रखने के लिए लॉग इन करें',
        authCreateAccount: 'अपना खाता बनाएं',
        authSignupSub: 'अपनी प्रोफ़ाइल सहेजें और अपने आवेदनों को ट्रैक करें',
        authEmail: 'ईमेल',
        authPassword: 'पासवर्ड',
        authEmailPh: 'you@example.com',
        authPasswordPh: '••••••••',
        authPasswordCreatePh: 'कम से कम 8 अक्षर',
        authName: 'नाम',
        authNameOptional: '(वैकल्पिक)',
        authNamePh: 'आपका नाम',
        authLogIn: 'लॉग इन',
        authLoggingIn: 'लॉग इन हो रहा है...',
        authCreate: 'खाता बनाएं',
        authCreating: 'खाता बना रहा है...',
        authPwTooShort: 'पासवर्ड कम से कम 10 अक्षर का होना चाहिए',
        authNoAccount: 'खाता नहीं है?',
        authHaveAccount: 'पहले से खाता है?',

        anActive: 'सक्रिय',
        anTopMatch: 'शीर्ष मिलान',
        anJobs: 'नौकरियां',
        anSaved: 'सहेजी गई',
        anUploadNew: 'नया अपलोड करें',
        anReRun: 'खोज फिर से चलाएं',
        anImproveStudio: 'स्टूडियो में सुधारें',
        anBiasingToward: 'मिलान को इस ओर निर्देशित कर रहे हैं:',
        anBiasingForward: 'हम मिलान को इस ओर निर्देशित करेंगे:',
        anClearIntent: 'इरादा साफ़ करें और पुनः क्रम दें',
        anLowMatchTitleA: 'आपका शीर्ष मिलान केवल ',
        anLowMatchTitleB: '% है।',
        anLowMatchSub: 'क्या आप चाहते हैं कि AI सहायक विशिष्ट रिज्यूमे बदलाव या वैकल्पिक जॉब टाइटल सुझाए?',
        anLowMatchGetTips: 'सुझाव पाएं',
        anLowMatchDismiss: 'खारिज करें',

        anMatchedJobs: 'मिलान वाली नौकरियां',
        anSortBest: 'सर्वश्रेष्ठ मिलान',
        anSortRecent: 'सबसे हाल का',
        anSortPay: 'सबसे अधिक वेतन',
        anFilters: 'फ़िल्टर:',
        anFilterRemote: 'रिमोट',
        anFilterFullTime: 'पूर्णकालिक',
        anFilter100k: '$100k+',
        anClearAll: 'सब साफ़ करें',
        anNoMatchesForFilters: 'इन फ़िल्टर से कोई नौकरी मेल नहीं खाती।',
        anClearFilters: 'फ़िल्टर साफ़ करें',

        sbYourProfile: 'आपकी प्रोफ़ाइल',
        sbTranslatedFrom: 'अनुवादित से',
        sbSummary: 'सारांश',
        sbTargetRoles: 'लक्षित भूमिकाएं',
        sbSkills: 'कौशल',
        sbExperience: 'अनुभव',
        sbEducation: 'शिक्षा',
        sbUsEquivalents: 'US समकक्ष',
        sbDegree: 'डिग्री',
        sbRecCerts: 'अनुशंसित प्रमाणन',
        sbImproveStudio: 'इस रिज्यूमे को स्टूडियो में सुधारें',

        viewJob: 'जॉब देखें',
        jobMarkApplied: 'आवेदन किया हुआ चिह्नित करें',
        jobApplied: 'आवेदन किया',
        jobSave: 'बाद के लिए सहेजें',
        jobUnsave: 'सहेजना रद्द करें',
        matchingJobs: 'आपके लिए मेल खाने वाली नौकरियां',
        searchingJobs: 'नौकरियां खोजी जा रही हैं...',
        noJobsFound: 'कोई नौकरी नहीं मिली।',

        resTitle: 'आपके रिज्यूमे',
        resEmpty: 'शुरू करने के लिए अपना पहला रिज्यूमे अपलोड करें।',
        resCount: (n) => `${n} सहेजे गए। सक्रिय एक जॉब मैच और चैट को संचालित करता है।`,
        resUploadNew: 'नया अपलोड करें',
        resEmptyTitle: 'अभी तक कोई रिज्यूमे नहीं',
        resEmptyDesc: 'विश्लेषण पृष्ठ पर अपना पहला रिज्यूमे अपलोड करें। AI अनुवाद करेगा, पार्स करेगा, और मेल खाने वाली नौकरियां ढूंढेगा।',
        resEmptyCta: 'अपना पहला रिज्यूमे अपलोड करें',
        resActiveBadge: 'सक्रिय',
        resSetActive: 'सक्रिय करें',
        resRename: 'नाम बदलें',
        resDelete: 'हटाएं',
        resSaveTip: 'सहेजें',
        resCancelTip: 'रद्द करें',
        resUploadedOn: 'अपलोड किया गया',
        resLoading: 'आपके रिज्यूमे लोड हो रहे हैं…',
        resConfirmDelete: (label) => `"${label}" हटाएं? यह पूर्ववत नहीं किया जा सकता।`,

        jpTitle: 'आपकी नौकरियां',
        jpSub: 'सहेजे गए बुकमार्क और आप जिन आवेदनों को ट्रैक कर रहे हैं।',
        jpTabSaved: 'सहेजी गई',
        jpTabApps: 'आवेदन',
        jpEmptySaved: 'अभी तक कोई सहेजी हुई नौकरी नहीं',
        jpEmptySavedDesc: 'इसे बाद के लिए सहेजने के लिए अपने मिलान में किसी भी जॉब पर दिल पर क्लिक करें।',
        jpFindJobs: 'नौकरियां ढूंढें',
        jpEmptyApps: 'अभी तक कोई आवेदन ट्रैक नहीं किया गया',
        jpEmptyAppsDesc: 'जब आप किसी जॉब पर आवेदन करते हैं, तो इसकी स्थिति को यहां ट्रैक करने के लिए "आवेदन किया हुआ चिह्नित करें" पर क्लिक करें।',
        jpUnsave: 'सहेजना रद्द करें',
        jpDelete: 'हटाएं',
        jpDeleteConfirm: 'इस आवेदन रिकॉर्ड को हटाएं?',
        jpNotes: 'नोट्स',
        jpNotesPh: 'मंगलवार साक्षात्कार, रिक्रूटर से संपर्क किया, आदि।',
        jpAppliedOn: 'आवेदन किया',
        jpLoading: 'आपकी नौकरियां लोड हो रही हैं…',
        jpStatusApplied: 'आवेदन किया',
        jpStatusInterviewing: 'साक्षात्कार',
        jpStatusOffered: 'ऑफर मिला',
        jpStatusRejected: 'अस्वीकृत',
        jpStatusWithdrawn: 'वापस लिया',

        stEditing: 'संपादन:',
        stManage: 'प्रबंधित करें',
        stReRankJobs: 'नौकरियां पुनः रैंक करें',
        stBuildUsResume: 'US रिज्यूमे बनाएं',
        stYourResume: 'आपका रिज्यूमे',
        stAiCoach: 'AI कोच',
        stExplainIn: 'इसमें समझाएं',
        stFocusLabel: 'कोच को किस पर ध्यान देना चाहिए?',
        stFocusOptional: '(वैकल्पिक)',
        stFocusPh: 'जैसे: नेतृत्व पर जोर दें, बुलेट छोटे करें',
        stGetSuggestions: 'सुझाव प्राप्त करें',
        stNewSuggestions: 'नए सुझाव',
        stCoaching: 'कोचिंग…',
        stCoachEmptyA: ' पर क्लिक करें ',
        stCoachEmptyB: ' इस रिज्यूमे को मजबूत करने के विशिष्ट तरीके देखने के लिए।',
        stCurrently: 'वर्तमान में',
        stSuggested: 'सुझाया गया',
        stApply: 'लागू करें',
        stSkip: 'छोड़ें',
        stTypeSummary: 'सारांश',
        stTypeBullet: 'अनुभव बुलेट',
        stTypeSkill: 'कौशल',
        stTypeNewSkill: 'नया कौशल',
        stTypeTargetRole: 'लक्षित भूमिका',
        stTypeCert: 'प्रमाणन',
        stVerbRewrite: 'फिर से लिखें',
        stVerbReplace: 'बदलें',
        stVerbAdd: 'जोड़ें',
        stEmptyTitle: 'अभी तक कोचिंग के लिए कोई रिज्यूमे नहीं',
        stEmptyDesc: 'पहले एक रिज्यूमे अपलोड करें — स्टूडियो आपको इसे पंक्ति-दर-पंक्ति सुधारने में मदद करेगा।',
        stUploadResumeBtn: 'रिज्यूमे अपलोड करें',
        stLoading: 'स्टूडियो लोड हो रहा है…',

        blTitle: 'US रिज्यूमे बनाएं',
        blTemplate: 'टेम्पलेट',
        blTemplateHybrid: 'हाइब्रिड',
        blTemplateChrono: 'कालक्रमिक',
        blTemplateSkillsFirst: 'कौशल-पहले',
        blTemplateHybridDesc: 'कौशल + कालक्रमिक — अप्रवासियों के लिए सर्वश्रेष्ठ',
        blTemplateChronoDesc: 'क्लासिक US प्रारूप — स्थिर करियर के लिए सर्वश्रेष्ठ',
        blTemplateSkillsDesc: 'कार्यात्मक — करियर परिवर्तकों / अंतराल के लिए सर्वश्रेष्ठ',
        blOutputLang: 'आउटपुट भाषा',
        blGenerate: 'US-अनुकूल रिज्यूमे बनाएं',
        blRebuild: 'पुनर्निर्माण',
        blBuilding: 'बना रहा है…',
        blPreviewNote: 'नीचे पूर्वावलोकन। ATS साइटों के लिए सादे टेक्स्ट के रूप में कॉपी करें, या Word के लिए .docx डाउनलोड करें।',
        blCopyText: 'टेक्स्ट कॉपी करें',
        blCopyMd: 'Markdown कॉपी करें',
        blDownloadDocx: '.docx डाउनलोड करें',

        uploadResume: 'रिज्यूमे अपलोड करें',
        uploadHint: 'PDF, Word या इमेज • कोई भी भाषा',
        analyzeButton: 'रिज्यूमे का विश्लेषण करें',
        analyzing: 'रिज्यूमे का विश्लेषण किया जा रहा है...',
        analysisComplete: 'विश्लेषण पूरा हुआ!',
        originalLanguage: 'मूल भाषा',
        skills: 'कौशल',
        experience: 'अनुभव',
        education: 'शिक्षा',
        usEquivalents: 'अमेरिकी समकक्ष और सिफारिशें',
        degreeEquivalent: 'डिग्री समकक्ष',
        recommendedCerts: 'अनुशंसित प्रमाणन',
        recommendedJobs: 'अनुशंसित जॉब टाइटल्स',
        suggestions: 'अमेरिकी नियोक्ताओं के लिए सुझाव',
        chatTitle: 'जॉब सर्च असिस्टेंट',
        chatSubtitle: 'हमेशा आपकी मदद के लिए यहाँ है',
        chatPlaceholder: 'मुझसे कुछ भी पूछें...',
        chatWelcome: 'नमस्ते! मैं आपका जॉब सर्च असिस्टेंट हूँ।',
        chatAskCoach: 'कोच से पूछें',

        commonError: 'कुछ गलत हुआ। कृपया पुनः प्रयास करें।',
        commonCopyBlocked: 'कॉपी विफल — आपके ब्राउज़र ने क्लिपबोर्ड एक्सेस को अवरुद्ध किया हो सकता है',
    },
};
